version: '3'

services:
  etl:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: kids-first/etl:0.0.1
    links:
      - elasticsearch
    container_name: kf-etl
    hostname: kf-etl
    environment:
        - KF_STUDY_ID="SD_YNSSAPHE"
        #- KF_STUDY_ID="UNKNOWN_STUDY"
        - KF_RELEASE_ID=RE_CEG0C8WK
        - KF_DRIVER_MEMORY=1g
    volumes:
      - "./kf-portal-etl-docker/kf_etl.conf:/kf-etl/conf/kf_etl.conf"
      - "./kf-portal-etl-docker/log4j.properties:/kf-etl/spark/conf/log4j.properties"
      - "./target/scala-2.11/kf-portal-etl.jar:/kf-etl/data/kf-portal-etl.jar"
      - "./kf-portal-etl-docker/mondo.tsv.gz:/kf-etl/mondo.tsv.gz"
      - "./kf-portal-etl-docker/ncit.tsv.gz:/kf-etl/ncit.tsv.gz"
      - "./kf-portal-etl-docker/hpo_terms.json:/kf-etl/hpo_terms.json"
      - "./kf-portal-etl-docker/duo_code/duo.csv:/kf-etl/duo.csv"
    ports:
      - "4040:4040"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: kf-es
    hostname: kf-es
    ports:
        - "9299:9200"
        - "9399:9300"
    environment:
      - discovery.type=single-node
      - cluster.name=kf-es
  kf-dataservice:
    container_name: kf-dataservice
    hostname: kf-dataservice
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./kf-portal-etl-docker/external/dataservice/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./kf-portal-etl-docker/external/dataservice/data:/data/www